### ISSUE TITLE
Reference book not working 

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#1160]
Contents are not loading . Next previous buttons not showing text properly 
![Z7frA5QeZi](https://user-images.githubusercontent.com/48617390/181484209-4895366f-5d82-49cb-8958-15fdc262e600.png)

**Comment by eliranwong** [comment]
thanks for reporting it, I will fix it.

**Comment by eliranwong** [comment]
fixed via https://github.com/eliranwong/UniqueBible/commit/149350c54dcd9d65d6382ea886530b8a6ce1af60

**Comment by onegladiator4u** [comment]
content is loading . Next previous buttons still not understandable
