### ISSUE TITLE
error message MXLinux installation

### ISSUE THREAD

**Issue by frank4532** [eliranwong/UniqueBible#577]
After a fresh installation of MX Linux Debian I got this error message

**This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.**

I tried to install some plugins  but I could not fix the problem. I tried also to reinstall UB.

**Comment by frank4532** [comment]
Problem solved

**Comment by frank4532** [comment]
UB works fine

**Comment by eliranwong** [comment]
@frank4532 may I ask how you solved it?

**Comment by frank4532** [comment]
I installed Lubuntu. I am happy with LXQT on my old hardware. I installed UB and works very well on Lubuntu.
For the plugins problem on MX I tried some solutions that I found on the Web but I was not able to fix the error.

**Comment by eliranwong** [comment]
thanks for sharing.  I am glad that the issue was solved.

**Comment by Zoomerhimmer** [comment]
I'm getting the same error on a debian-10 system. I installed qt5dxcb-plugin as suggested on the Linux Install wiki. But that doesn't solve the issue.

**Comment by otseng** [comment]
It required a lot of tinkering around to get it working with Debian.  But, here's some tips:
https://github.com/eliranwong/UniqueBible/wiki/Install-on-Linux#debian-troubleshooting-tips

**Comment by Zoomerhimmer** [comment]
This worked for me. Thanks a lot.
